import RootLayout from "@/components/root_layout";
import React from "react";
import "@/styles/globals.css";
import Head from "next/head";

const App = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <link
          rel="icon"
          type="image/png"
          sizes="12x32"
          href="/images/logo.png"
        ></link>
        <title>Different Treks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </Head>
      <div>
        <RootLayout>
          <Component {...pageProps} />
        </RootLayout>
      </div>
    </>
  );
};

export default App;
