import Homepage from "@/components/homepage";
import Search from "@/components/search";
import Slider from "@/components/slider";
import Head from "next/head";
import Image from "next/image";
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Different Treks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Slider />
      <Search />
      <Homepage />
    </>
  );
}
